# NUM NUM.... NUMPYYY

In [2]:
import numpy as np

Know the version of numpy

In [3]:
print(np.__version__)

1.16.1


Lets create an array of size 10 containing only ZEROS

In [4]:
# KIDS
x = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
x = np.array(x)
print(x)

# MEN
x = []
for _ in range(10):
    x.append(0)
x = np.array(x)
print(x)

# LEGENDS
x = [0 for x in range(10)]
x = np.array(x)
print(x)

# ULTRA LEGENDS
x = np.zeros(10, dtype='int')
print(x)
print("Type: ", type(x))
print("Numpy datatype: ", x.dtype)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]
Type:  <class 'numpy.ndarray'>
Numpy datatype:  int32


Say you wanna learn some more about a method don't afraid to ask Mr.np

In [5]:
np.info(np.dot)

dot(a, b, out=None)

Dot product of two arrays. Specifically,

- If both `a` and `b` are 1-D arrays, it is inner product of vectors
  (without complex conjugation).

- If both `a` and `b` are 2-D arrays, it is matrix multiplication,
  but using :func:`matmul` or ``a @ b`` is preferred.

- If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
  and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.

- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
  the last axis of `a` and `b`.

- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
  sum product over the last axis of `a` and the second-to-last axis of `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

Parameters
----------
a : array_like
    First argument.
b : array_like
    Second argument.
out : ndarray, optional
    Output argument. This must have the exact kind that would be returned
    if it was not used. In particular, it must have the right type, 

### Create a matrix

In [6]:
x_matrix = np.arange(5,14).reshape(3,3)
print("Matrix:\n", x_matrix)
print("Shape: ", x_matrix.shape)

Matrix:
 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
Shape:  (3, 3)


In [7]:
new_x = x.reshape(2,5)
print("new_x:\n", new_x)
print("shape: ", new_x.shape)

new_x:
 [[0 0 0 0 0]
 [0 0 0 0 0]]
shape:  (2, 5)


Now Lets create an identity matrix

In [8]:
identity_matrix = np.eye(5)
print("Identity matrix:\n", identity_matrix)

Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Now lets randomize the elements

In [9]:
x = np.random.random((3,3,3)) 
print(x)

[[[0.38784717 0.28632663 0.62716804]
  [0.03719529 0.1165078  0.32438597]
  [0.69045049 0.76388666 0.89089628]]

 [[0.548116   0.26255383 0.07095688]
  [0.51827822 0.97364918 0.26646481]
  [0.89065578 0.26715992 0.29576837]]

 [[0.17168495 0.75409874 0.9956962 ]
  [0.44269765 0.4838447  0.78139216]
  [0.60876179 0.23788894 0.58401887]]]


Get the max and min value in that 3D matrix

In [10]:
print(f"Min_value: {x.min()}\nMax_value: {x.max()}")

Min_value: 0.037195292895982446
Max_value: 0.9956961996206188


Create a 10 x 10 array with 1 on the border and 0 inside

In [11]:
answer = np.ones(100).reshape(10,10)
answer[1:-1, 1:-1] = 0
print(f"Answer:\n{answer}")

Answer:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [12]:
x = np.random.random((3,3))
y = np.random.random((3,3))

z =np.add(x,y)
print("x:\n", x)
print("y:\n", y)
print("addition:\n",z)

x:
 [[0.94832512 0.40079536 0.24797745]
 [0.10666379 0.92979694 0.38779208]
 [0.06584949 0.16590619 0.70378903]]
y:
 [[0.20343333 0.86955103 0.47060159]
 [0.81087136 0.89126939 0.31432925]
 [0.12593359 0.94383726 0.60560478]]
addition:
 [[1.15175845 1.27034639 0.71857904]
 [0.91753516 1.82106633 0.70212133]
 [0.19178309 1.10974345 1.30939381]]


In [13]:
print(f"dot product:\n{np.dot(x,y)}")

dot product:
[[0.54914311 1.41588407 0.72244134]
 [0.82448074 1.28746177 0.57730726]
 [0.23655524 0.86938891 0.50935604]]
